apiVersion: batch/v1
kind: Job
metadata:
  name: default-domain
  namespace: knative-serving
  labels:
    app: "default-domain"
    app.kubernetes.io/component: default-domain-job
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: devel
spec:
  template:
    metadata:
      labels:
        app: "default-domain"
        app.kubernetes.io/component: default-domain-job
        app.kubernetes.io/name: knative-serving
        app.kubernetes.io/version: devel
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: controller
      containers:
      - name: default-domain
        image: "gcr.io/knative-releases/knative.dev/serving/cmd/default-domain@sha256:649934bce92e4cf734cb39f19305cc46af015e391c9b0f81376d7829df95ca69"
        args: ["-magic-dns=nip.io"]
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            port: 8080
        livenessProbe:
          httpGet:
            port: 8080
          failureThreshold: 6
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      restartPolicy: Never
  backoffLimit: 10

---
apiVersion: v1
kind: Service
metadata:
  name: default-domain-service
  namespace: knative-serving
  labels:
    app: default-domain
    app.kubernetes.io/component: default-domain-job
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: devel
spec:
  selector:
    app: default-domain
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: ClusterIP
