name: Stop linode instance

on:
  workflow_call:
    inputs:
      artifact_name: 
        required: true
        type: string
    secrets:
      LINODE_TOKEN:
        required: true
      ROOT_PASSWORD:
        required: true
      SSH_KEY: 
        required: true

jobs:
  linode_instance_destroy:
    runs-on: ubuntu-latest
    steps:

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ inputs.artifact_name }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.5"

      - name: terraform init
        working-directory: ${{ inputs.artifact_name }}
        run: terraform init

      - name: terraform plan -destroy
        working-directory: ${{ inputs.artifact_name }}
        env:
          TF_VAR_linode_token: ${{ secrets.LINODE_TOKEN }}
          TF_VAR_ssh_key: ${{ secrets.SSH_KEY }}
          TF_VAR_root_password: ${{ secrets.ROOT_PASSWORD }}
          TF_VAR_node_name: "mindwm-ci-${{ github.run_number }}-${{ github.run_attempt }}"
        run: terraform plan

      - name: terraform destroy -auto-approve
        working-directory: ${{ inputs.artifact_name }}
        env:
          TF_VAR_linode_token: ${{ secrets.LINODE_TOKEN }}
          TF_VAR_root_password: ${{ secrets.ROOT_PASSWORD }}
          TF_VAR_node_name: "mindwm-ci-${{ github.run_number }}-${{ github.run_attempt }}"
          TF_VAR_ssh_key: ${{ secrets.SSH_KEY }}
        run: terraform destroy -auto-approve
