name: Add PR comment

on:
  workflow_call:
    inputs:
      artifact_name:
        required: true
        type: string

jobs:
  upload_allure_report:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: artifact_dir

      - name: Allure Report Action
        uses: mgrybyk-org/allure-report-branch-js-action@v1
        id: allure
        continue-on-error: true
        with:
          list_dirs: true
          report_id: 'ci'
          gh_pages: 'gh-pages'
          report_dir: 'artifact_dir/allure-results'

      - name: Comment PR with Allure Report link
        continue-on-error: true
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            ${{ steps.allure.outputs.test_result_icon }} [Allure Report](${{ steps.allure.outputs.report_url }}) | [History](${{ steps.allure.outputs.report_history_url }})
          comment_tag: allure_report
          mode: recreate
